name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.7', '3.11']
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          python-version: ${{ matrix.python_version }}

      - name: Check Python versions
        shell: bash -l {0}
        run: |
          python --version
          which python
          # Otherwise we get errors on Python 3.6 due to https://stackoverflow.com/questions/38257138/jupyter-no-such-kernel-named-python3
          conda install -y nb_conda_kernels jupyter_server ipykernel
          ipython kernel install --name "python3" --user

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install -r testing-requirements.txt
          pip install .

      - name: Test
        shell: bash -l {0}
        run: |
          pytest -s -v --cov=rampwf --cov-report=xml rampwf

      - uses: codecov/codecov-action@v3
        with:
          verbose: true


  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install flake8

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 rampwf
