name: main

on:
  push:
    branches: [master, gh-actions-with-upstream-branch]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        python_version: [3.6, 3.7]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          python-version: ${{ matrix.python_version }}

      - name: Check Python versions
        shell: bash -l {0}
        run: |
          python --version
          which python
          # Otherwise we get errors on Python 3.6 due to https://stackoverflow.com/questions/38257138/jupyter-no-such-kernel-named-python3
          conda install -y nb_conda_kernels

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install -r testing-requirements.txt
          pip install .

      - name: Test
        shell: bash -l {0}
        run: |
          pytest -s -v --cov=rampwf rampwf

      - uses: codecov/codecov-action@v2
        with:
          verbose: true


  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install flake8

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 rampwf
